parameters:
    database_name:     homestead
    database_user:     root
    database_password: root
    # You should uncomment this if you want use pdo_sqlite
    # database_path: "%kernel.root_dir%/data.db3"

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_port:       ~
    mailer_user:       ~
    mailer_password:   ~

    # A secret key that's used to generate certain security-related tokens
    secret:            ThisTokenIsNotSoSecretChangeIt

    # Configuration for facebook
    facebook_app_id:     <your number>
    facebook_app_secret: <your number>

    google_app_id:     <your number>
    google_app_secret: <your number>

    # Configuration for CMF
    admin_address: super@mail.com
    admin_name: Admin
    link:  https://sonata-cmf.org
    title: Symfony CMF

    # Sonata Page Options
    sonata_page.varnish.command: if [ ! -r "/etc/varnish/secret" ]; then echo "VALID ERROR :/"; else varnishadm -S /etc/varnish/secret -T 127.0.0.1:6082 {{ COMMAND }} "{{ EXPRESSION }}"; fi; # you need to adapt this line to work with your configuration