sonata_page:
    slugify_service:   sonata.core.slugify.cocur # old BC value is sonata.core.slugify.native
    # Generates a snapshot when a page is saved (from the admin)
    direct_publication: false # or %kernel.debug% if you want to publish in dev mode (but not in prod)

    multisite: host
    use_streamed_response: true # set the value to false in debug mode or if the reverse proxy does not handle streamed response
    ignore_route_patterns:
        - ^(.*)admin(.*)   # ignore admin route, ie route containing 'admin'
        - ^_(.*)          # ignore symfony routes

    ignore_routes:
        - sonata_page_cache_esi
        - sonata_page_cache_ssi
        - sonata_page_js_sync_cache
        - sonata_page_js_async_cache
        - sonata_cache_esi
        - sonata_cache_ssi
        - sonata_cache_js_async
        - sonata_cache_js_sync
        - sonata_cache_apc

    ignore_uri_patterns:
        - ^/admin\/   # ignore admin route, ie route containing 'admin'

    page_defaults:
        homepage: { decorate: true} # disable decoration for homepage, key - is a page route

    default_template: default # template key from templates section, used as default for pages
    templates:
        default:
            path: 'ApplicationSonataPageBundle::layout.html.twig'
            name: 'default'
            containers:
                header:
                    name: content_header
                content_top:
                    name: content_top
                content:
                    name: content
                content_bottom:
                    name: content_bottom
                footer:
                    name: content_footer
            matrix:
                layout: |
                        HHHHHHHH
                        TTTTBBBB
                        TTTTBBBB
                        TTTTBBBB
                        TTTTBBBB
                        CCCCCCCC
                        CCCCCCCC
                        FFFFFFFF

                mapping:
                        H: content_header
                        T: content_top
                        C: content
                        B: content_bottom
                        F: content_footer
        2columns:
            path: 'ApplicationSonataPageBundle::2columns_layout.html.twig'
            name: '2 columns layout'
            inherits_containers: default
            containers:
                left_col:
                    name: left_col
                    blocks:
                        - sonata.media.block.media
                        - sonata.media.block.gallery
                        - sonata.media.block.feature_media
                content:
                    name: Main content
                    blocks:
                        - sonata.media.block.media
                right_col:
                    name: right_col
                    blocks:
                        - sonata.news.block.recent_posts
                        - sonata.order.block.recent_orders
                        - sonata.product.block.recent_products
            matrix:
                layout: |
                        HHHHHHHHHH
                        TTTTTTTTTT
                        TTTTTTTTTT
                        LLLCCCCRRR
                        LLLCCCCRRR
                        BBBBBBBBBB
                        BBBBBBBBBB
                        FFFFFFFFFF
                mapping:
                       H: header
                       T: content_top
                       L: left_col
                       R: right_col
                       C: content
                       B: content_bottom
                       F: footer
    # manage the http errors
    catch_exceptions:
        not_found: [404]    # render 404 page with "not_found" key (name generated: _page_internal_error_{key})
        fatal:     [500]    # so you can use the same page for different http errors or specify specific page for each error
